### PR TITLE
should inherit from an explicit WfsRails::ApplicationController, not …

### PR DESCRIPTION
**Pull request by mejackreed**
…just any ApplicationController

### CODE REVIEW

**Comment by cbeer** [comment]
Is this project running on travis yet?

**Comment by mejackreed** [comment]
No, I should do that.

**Comment by cbeer** [comment]
:+1:

**Comment by mjgiarlo** [comment]
Inheriting from ApplicationController is fairly standard, isn't it? I'm not against the change but I'm thinking it'd be good to document the rationale for deviating from is arguably Rails standard practice so that folks don't think it's a bug or an anti-pattern.

**Comment by mjgiarlo** [comment]
What if I include your gem in my app and I want it to inherit my application settings, such as systemwide authN/Z? I suspect that's why controllers, even in engines, just inherit from ApplicationController.

If OTOH you're certain that you want this engine to be isolated from containing applications, you might want to look into the isolated engine pattern. If you haven't used it before, do a browser find on "isolate" here for more info: http://guides.rubyonrails.org/engines.html

**Comment by cbeer** [comment]
I don't think that's the case here, so :+1: to `isolate_namespace`

**Comment by mejackreed** [comment]
Thanks for the suggestion. The intent here is to provide isolation from the inheritance of a consuming applications `ApplicationController`. I did have the `isolate_namespace` implemented here: https://github.com/sul-dlss/wfs_rails/blob/master/lib/wfs_rails/engine.rb#L3

But for some reason all `before_action`s coming from a consumer are being forced upon WfsRails. Since we are using WfsRails, not as an implemented engine in the application, but as a booted Rack application we need to provide a workaround to get around `before_actions` that really shouldn't be followed.

Monkey patching in an initializer  isn't an appropriate approach either, as Rails autoloading will overwrite those patches. Would love some feedback on an alternative approach or a way to better implement `isolate_namespace`.

**Comment by mjgiarlo** [comment]
Interesting. I'm reading about the interaction between `isolate_namespace` and controllers in engines here: https://bibwild.wordpress.com/2012/05/10/the-semi-isolated-rails-engine/ Could be some hints there.

**Comment by mjgiarlo** [comment]
In short, I *think* the explicit namespace is A-OK, but it may be useful to take snippets from your comment above, @mejackreed, and add them as as a comment on the class so that someone doesn't undo your good work later.

**Comment by mejackreed** [comment]
Thanks @mjgiarlo . I took your suggestion and added a comment so others would know.

**Comment by mjgiarlo** [comment]
:+1: :shipit:

**Pull request merged**
